# Generated by Django 5.2.4 on 2025-07-27 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('job_cst_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_cst_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequiredSkill',
            fields=[
                ('job_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_skill_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('payment_option', models.IntegerField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('job_location', models.CharField(max_length=500)),
                ('application_deadline', models.DateTimeField()),
                ('job_post_date', models.DateTimeField(auto_now_add=True)),
                ('job_expire_date', models.DateTimeField()),
                ('job_is_active', models.BooleanField(default=True)),
                ('job_viewcount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('job_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jobcategory')),
                ('required_skills', models.ManyToManyField(to='api.jobrequiredskill')),
            ],
        ),
    ]
