# Generated by Django 5.2.4 on 2025-07-27 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_jobcategory_jobrequiredskill_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='job_category',
        ),
        migrations.RemoveField(
            model_name='job',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='job',
            name='user',
        ),
        migrations.DeleteModel(
            name='JobCategory',
        ),
        migrations.DeleteModel(
            name='JobRequiredSkill',
        ),
        migrations.DeleteModel(
            name='Job',
        ),
    ]
