# Generated by Django 5.2.4 on 2025-07-27 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_job_job_category_remove_job_required_skills_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_cat_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequiredSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_skill_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_option_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('job_location', models.CharField(max_length=500)),
                ('job_post_date', models.DateTimeField(auto_now_add=True)),
                ('application_deadline', models.DateTimeField()),
                ('job_expire_date', models.DateTimeField()),
                ('job_is_active', models.BooleanField(default=True)),
                ('job_viewcount', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('job_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jobcategory')),
                ('required_skills', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.jobrequiredskill')),
                ('payment_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.paymentoption')),
            ],
        ),
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=500)),
                ('image_upload_date', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.job')),
            ],
        ),
    ]
