# Generated by Django 5.2.4 on 2025-07-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='suffix',
            field=models.CharField(blank=True, choices=[('', ''), ('Jr', 'Jr'), ('Sr', 'Sr'), ('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V')], max_length=5, null=True),
        ),
    ]
