# Generated by Django 5.2.4 on 2025-08-04 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_verification_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_front', models.URLField(max_length=500)),
                ('id_back', models.URLField(blank=True, max_length=500, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdentificationCardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='identification_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profile', to='accounts.identificationcard'),
        ),
        migrations.AddField(
            model_name='identificationcard',
            name='card_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cards', to='accounts.identificationcardtype'),
        ),
    ]
