# Generated by Django 5.2.4 on 2025-08-06 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_address_alter_userprofile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
