# Generated by Django 5.2.4 on 2025-08-06 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_cover_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationcard',
            name='id_back',
            field=models.FileField(blank=True, null=True, upload_to='id_cards/'),
        ),
        migrations.AlterField(
            model_name='identificationcard',
            name='id_front',
            field=models.FileField(blank=True, null=True, upload_to='id_cards/'),
        ),
    ]
