# Generated by Django 5.2.4 on 2025-08-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_identificationcard_id_back_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identificationcard',
            name='id_back',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='identificationcard',
            name='id_front',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
