# Generated by Django 5.2.4 on 2025-07-30 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_rating', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
