# Generated by Django 5.2.4 on 2025-07-30 14:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_rating', '0002_delete_userreview'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrating',
            old_name='ratee',
            new_name='rated_user',
        ),
        migrations.AlterUniqueTogether(
            name='userrating',
            unique_together={('rater', 'rated_user')},
        ),
    ]
