# Generated by Django 5.2.4 on 2025-07-28 09:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('job_cat_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_cat_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('payment_option_id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_option_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_location', models.CharField(max_length=100)),
                ('job_post_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('application_deadline', models.DateTimeField()),
                ('job_expire_date', models.DateTimeField()),
                ('job_is_active', models.BooleanField(default=True)),
                ('job_viewcount', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobcategory')),
            ],
        ),
        migrations.CreateModel(
            name='JobImage',
            fields=[
                ('job_image_id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.URLField()),
                ('image_upload_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='jobs.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('job_skill_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_skill_name', models.CharField(max_length=100)),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='jobs.jobcategory')),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.jobskill'),
        ),
        migrations.AddField(
            model_name='job',
            name='payment_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.paymentoption'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('application_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('REJECTED', 'Rejected'), ('SHORTLISTED', 'Shortlisted'), ('ACCEPTED', 'Accepted')], default='PENDING', max_length=20)),
                ('applicant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.job')),
            ],
            options={
                'unique_together': {('job_id', 'applicant_id')},
            },
        ),
    ]
