# Generated by Django 5.2.4 on 2025-08-07 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_remove_job_required_skills_job_required_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cover_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
