# Generated by Django 5.2.4 on 2025-08-08 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_remove_job_job_location_job_address_job_barangay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='map_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
