# Generated by Django 5.2.4 on 2025-08-08 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_latitude_job_longitude_job_map_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='job',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='job',
            name='map_link',
        ),
    ]
