# Generated by Django 5.2.4 on 2025-08-08 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_remove_job_latitude_remove_job_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='vacancies',
            field=models.PositiveIntegerField(default=1, help_text='Number of persons needed for this job'),
        ),
    ]
