# Generated by Django 5.2.4 on 2025-08-09 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_vacancies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_expire_date',
            field=models.DateField(),
        ),
    ]
