# Generated by Django 5.2.4 on 2025-08-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_job_application_deadline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
